---
title: "Precipitation patterns from 1981-1989"
output: 
  flexdashboard::flex_dashboard:
    orientation: row
  runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(janitor)
library(stringr)
library(forcats)
library(viridis)
library(plotly)
library(ggplot2)
library(ggthemes)
library(shiny)
```

```{r accessing_and_cleaning_data}
ny_noaa_data_tidy = read_csv("./nynoaadat.zip") %>%
  clean_names() %>%
  drop_na() %>%
  separate(date, into = c("year", "month", "day"), "-") %>%
  mutate(month = as.factor(month), prcp = as.numeric(prcp), tmin = as.numeric(tmin), 
         prcp = prcp / 10,
         tmax = as.numeric(tmax),
         tmax = tmax / 10,
         tmin = tmin / 10) %>% 
  mutate(month = recode(month,
                          "01" = "January",
                          "02" = "February",
                          "03" = "March",
                          "04" = "April",
                          "05" = "May",
                          "06" = "June",
                          "07" = "July",
                          "08" = "August",
                          "09" = "September",
                          "10" = "October",
                          "11" = "November",
                          "12" = "December")) %>%
  select (year, month, day, prcp, tmin, snow, tmax, snow) %>%
  mutate(snowfall = ifelse(snow > 0, "Yes", "No"),) %>% 
  filter(year <= "1989")
```

Column {.sidebar}
-----------------------------------------------------------------------

```{r sidebar}
max_temp = ny_noaa_data_tidy %>% 
  mutate(tmax = as.numeric(tmax)) %>% 
  pull(tmax) %>% 
  max()

min_temp = ny_noaa_data_tidy %>% 
  mutate(tmax = as.numeric(tmax)) %>% 
  pull(tmax) %>% 
  min()
  
# sliderInput widget
sliderInput("temp_range", label = h3("Choose max temp range"), min = min_temp, 
        max = max_temp, value = c(-20, 40))

snowfall = ny_noaa_data_tidy %>% distinct(snowfall) %>% pull()

# radioButtons widget
radioButtons("snowfall", label = h3("Did it snow that day?"),
    choices = snowfall, 
    selected = "No")
```


Row
-----------------------------------------------------------------------

### Monthly patterns of precipitation from 1981 to 1989

```{r}
renderPlotly({ny_noaa_data_tidy %>%
  group_by(month, year) %>%
  summarize(average_prcp = mean(prcp, na.rm = TRUE)) %>%
  ungroup() %>% 
  plot_ly(x = ~month, y = ~average_prcp, type = "scatter", mode = "lines+markers",
          color = ~year)})
```

Row {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Range of minimun temperature in degrees C from 1981-1989

```{r chart_b}
renderPlotly({ny_noaa_data_tidy %>%
   filter(tmax %in% input$temp_range[1]:input$temp_range[2],
          snowfall == input$snowfall) %>% 
   plot_ly(y = ~tmin, x = ~year, color = ~year, type = "box",
          colors = "Set2")})
```

### Variation in precipitation depending on average minimun temperature

```{r}
renderPlotly({ny_noaa_data_tidy %>% 
               filter(day %in% sample(ny_noaa_data_tidy$day, size = 5, replace = FALSE),
                      prcp < 2000) %>% 
               plot_ly(x = ~tmin, y = ~prcp, type = "scatter", mode = "markers")})
```
